apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ts4mzwuku-go 
  janus-idp.io/tekton: ts4mzwuku-go
  backstage.io/kubernetes-id: ts4mzwuku-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ts4mzwuku-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml